version: '3.8'

services:
  # Discord bot service
  bot:
    image: yourusername/matcherino-bot:latest  # Replace with your Docker Hub username
    container_name: matcherino-bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db/matcherino
      - MATCHERINO_TOURNAMENT_ID=${MATCHERINO_TOURNAMENT_ID}
    volumes:
      - ./cache:/app/cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: matcherino-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=matcherino
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    name: matcherino-postgres-data 