name: Build and Publish to GHCR

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:  # For manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/matcherino-bot:latest
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}/matcherino-bot:{1}', github.repository_owner, github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 